apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-10-hd
  labels:
    app: task-10-hd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-10-hd
  template:
    metadata:
      labels:
        app: task-10-hd
    spec:
      containers:
      - name: task-10-hd
        image: gcr.io/sit-437003/book-catalog:latest
        imagePullPolicy: Always 
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: gcr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: task-10-hd-service
spec:
  selector:
    app: task-10-hd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
